version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns: ['*']

  - package-ecosystem: npm
    directories:
      - /
      - /benchmarks
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: development
        update-types: [minor, patch]
