// Stands in for @nestjs/axios's `../lib/index.js` (its built entry point).
// jest.config.js (generated by run.mjs) maps that specifier here via
// moduleNameMapper, so the copied @nestjs/axios spec files import THIS
// package's HttpModule/HttpService instead, unmodified otherwise.
// PROTOTYPE_REPO_LIB is injected by run.mjs (absolute path to this repo's
// built `lib/index.js`) so the shim works no matter where it's invoked from.
const path = require('node:path');

const repoLib = process.env.PROTOTYPE_REPO_LIB;
if (!repoLib) {
  throw new Error(
    'lib-index shim: PROTOTYPE_REPO_LIB env var not set (run via run.mjs)',
  );
}

const built = require(path.resolve(repoLib));

module.exports = {
  HttpModule: built.HttpModule,
  HttpService: built.HttpService,
};
